# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
